import type { LucideIcon } from 'lucide-react';
import {
  Megaphone,
  MessageCircle,
  Mail,
  BarChart3,
  Music2,
  Activity,
  Link2,
  GitBranch,
  Trophy,
  ShoppingCart,
  Clock3,
  Workflow,
  Users,
  FileBarChart,
  CreditCard,
  RotateCcw,
  Target,
  Send,
  Gauge,
  Bot,
  ShieldCheck,
  Tags,
  Compass,
  FileCheck,
  Zap,
  Eye,
} from 'lucide-react';

export type VideoScreen = {
  slug: string;
  titulo: string;
  subtitulo: string;
  icon: LucideIcon;
  grupo: 'marketing' | 'remarketing';
  badge?: string;
  tabs: string[];
  acoes: string[];
};

export const marketingScreens: VideoScreen[] = [
  {
    slug: 'dashboard',
    titulo: 'Dashboard Marketing',
    subtitulo: 'Visão executiva de ROI, ROAS, vendas atribuídas e desempenho de mídia.',
    icon: Gauge,
    grupo: 'marketing',
    tabs: ['Visão Geral', 'Evolução Diária', 'Canais Ativos', 'Campanhas em Destaque'],
    acoes: ['Nova Campanha', 'Sincronizar Métricas', 'Gerar UTM', 'Exportar Relatório'],
  },
  {
    slug: 'campanhas',
    titulo: 'Campanhas Multicanais',
    subtitulo: 'Gestão unificada de anúncios em Meta, Google, TikTok e Spotify.',
    icon: Megaphone,
    grupo: 'marketing',
    tabs: ['Todas', 'Ativas', 'Agendadas', 'Pausadas', 'Finalizadas', 'Rascunhos'],
    acoes: ['Nova Campanha', 'Importar Público', 'Usar Modelo Pronto'],
  },
  {
    slug: 'campanhas-prontas',
    titulo: 'Campanhas Prontas',
    subtitulo: 'Modelos pré-configurados para todas as fases do ciclo de venda do evento.',
    icon: Zap,
    grupo: 'marketing',
    badge: 'PRONTO',
    tabs: ['Pré-venda', 'Lançamento Lote 1', 'Virada de Lote', 'Últimos Ingressos', 'Sessão Extra'],
    acoes: ['Ativar Modelo', 'Personalizar Cópias'],
  },
  {
    slug: 'status-real',
    titulo: 'Status Real & Telemetria de Entrega',
    subtitulo: 'Monitoramento ao vivo de entrega, impressões 6h, diagnósticos e sincronização.',
    icon: Activity,
    grupo: 'marketing',
    badge: 'AO VIVO',
    tabs: ['Meta Ads', 'Google Ads', 'TikTok Ads', 'Spotify Ads', 'Erros & Diagnósticos'],
    acoes: ['Sincronizar Agora', 'Diagnóstico Geral', 'Reprocessar Rejeições'],
  },
  {
    slug: 'meta',
    titulo: 'Meta Ads & Pixel / CAPI',
    subtitulo: 'Rastreamento Server-Side via Conversions API (CAPI) e gestão de múltiplos pixels.',
    icon: Target,
    grupo: 'marketing',
    badge: 'CAPI',
    tabs: ['Pixels Ativos', 'Conversions API (CAPI)', 'Qualidade de Correspondência', 'Logs de Eventos'],
    acoes: ['Testar Evento CAPI', 'Configurar Pixel', 'Health Check'],
  },
  {
    slug: 'google-analytics',
    titulo: 'Google Analytics 4 (GA4)',
    subtitulo: 'Measurement Protocol, funil de compras e-commerce e DebugView em tempo real.',
    icon: BarChart3,
    grupo: 'marketing',
    badge: 'GA4',
    tabs: ['Visão Geral & Desempenho', 'Funil de Compras E-commerce', 'Canais de Aquisição', 'DebugView em Tempo Real', 'Configuração & Consent Mode'],
    acoes: ['Enviar Ping DebugView', 'Testar Protocolo', 'Validar Consent v2'],
  },
  {
    slug: 'tiktok',
    titulo: 'TikTok Ads & Events API',
    subtitulo: 'Spark Ads, TikTok Pixel, Events API e públicos virais de engajamento.',
    icon: Activity,
    grupo: 'marketing',
    badge: 'PIXEL',
    tabs: ['Campanhas & Spark Ads', 'TikTok Pixel & Events API', 'Públicos Virais & Engajamento', 'Logs de Transmissão'],
    acoes: ['Testar Conexão TikTok', 'Criar Spark Ad', 'Sincronizar Audiência'],
  },
  {
    slug: 'spotify',
    titulo: 'Spotify Ads & CAPI Áudio',
    subtitulo: 'Campanhas de áudio, atribuição de vendas por UTM, CAPI e comparativo omnichannel.',
    icon: Music2,
    grupo: 'marketing',
    badge: 'ÁUDIO',
    tabs: ['Campanhas no Spotify', 'Atribuição de Vendas UTM', 'Spotify CAPI & Eventos', 'Comparativo Omnichannel'],
    acoes: ['Sincronizar', 'Configurar Credenciais', 'Testar CAPI Áudio', 'Nova Campanha Spotify'],
  },
  {
    slug: 'whatsapp',
    titulo: 'WhatsApp Marketing & CRM',
    subtitulo: 'Disparos oficiais Meta Cloud API, templates pré-aprovados com live preview e fila.',
    icon: MessageCircle,
    grupo: 'marketing',
    badge: 'OFICIAL',
    tabs: ['Campanhas de Disparo', 'Templates Oficiais & Live Preview', 'Jornadas & Automações', 'Histórico & Fila', 'Audiências & LGPD'],
    acoes: ['Nova Campanha WhatsApp', 'Validar Template', 'Simular Mensagem'],
  },
  {
    slug: 'email',
    titulo: 'E-mail Marketing & Entregabilidade',
    subtitulo: 'Disparos em lote, templates responsivos, testes A/B e logs SMTP auditáveis.',
    icon: Mail,
    grupo: 'marketing',
    tabs: ['Campanhas de E-mail', 'Templates & Preview', 'Testes A/B & Automações', 'Logs SMTP & Entregabilidade', 'Segmentação de Leads'],
    acoes: ['Novo Disparo', 'Testar Envio', 'Validar DKIM/SPF'],
  },
  {
    slug: 'automacoes',
    titulo: 'Automações & Jornadas de Marketing',
    subtitulo: 'Réguas multi-canais para abandono, virada de lote e engajamento pós-compra.',
    icon: Workflow,
    grupo: 'marketing',
    tabs: ['Jornadas Ativas', 'Gatilhos & Eventos', 'Histórico de Execuções', 'Templates Vinculados'],
    acoes: ['Nova Jornada', 'Pausar Todas', 'Testar Disparo'],
  },
  {
    slug: 'cupons',
    titulo: 'Cupons & Descontos Promocionais',
    subtitulo: 'Gestão de códigos promocionais com travas de uso, limite por CPF e setor.',
    icon: Tags,
    grupo: 'marketing',
    tabs: ['Cupons Ativos', 'Histórico de Usos', 'Regras de Restrição', 'Relatório de Descontos'],
    acoes: ['Novo Cupom', 'Exportar Códigos'],
  },
  {
    slug: 'utm',
    titulo: 'Central UTM & Links Rastreáveis',
    subtitulo: 'Gerador inteligente de parâmetros UTM, QR Codes SVG dinâmicos e funil por link.',
    icon: Link2,
    grupo: 'marketing',
    badge: 'UTM / QR',
    tabs: ['URLs Rastreáveis', 'Funil por Link', 'Evolução por Dia', 'Comparador de URLs', 'Diagnóstico & Insights'],
    acoes: ['Nova UTM', 'Comparar URLs', 'Baixar QR Code SVG', 'Copiar Link Rápido'],
  },
  {
    slug: 'afiliados',
    titulo: 'Afiliados & Promoters',
    subtitulo: 'Rede de promotores comissionados, links dedicados e extrato de repasse.',
    icon: Users,
    grupo: 'marketing',
    tabs: ['Promoters Ativos', 'Links de Afiliado', 'Extrato de Comissões', 'Regras de Pagamento'],
    acoes: ['Convidar Promoter', 'Aprovar Comissões'],
  },
  {
    slug: 'pixels',
    titulo: 'Pixels & Conversões (Multi-Pixel)',
    subtitulo: 'Central de controle de múltiplos pixels e servidores CAPI por evento.',
    icon: Target,
    grupo: 'marketing',
    badge: 'MULTI-PIXEL',
    tabs: ['Pixels Vinculados', 'Saúde dos Disparos', 'Mapeamento de Eventos', 'Logs de Transmissão'],
    acoes: ['Adicionar Pixel', 'Testar Ping Geral'],
  },
  {
    slug: 'atribuicao',
    titulo: 'Atribuição Multicanal & Jornadas',
    subtitulo: 'Comparação de modelos de atribuição, jornada multi-touch e ranking de ROAS.',
    icon: GitBranch,
    grupo: 'marketing',
    tabs: ['Comparativo de Modelos', 'Jornadas Multi-Touch', 'Ranking de Eficiência', 'Matriz de Canais'],
    acoes: ['Exportar Matriz', 'Recalcular Atribuição'],
  },
  {
    slug: 'relatorios',
    titulo: 'Relatórios de Marketing',
    subtitulo: 'Consolidação analítica de campanhas, CPA, CAC, ROAS e conversão.',
    icon: FileBarChart,
    grupo: 'marketing',
    tabs: ['Relatório Geral', 'Performance por Canal', 'Auditoria de UTMs', 'Rentabilidade'],
    acoes: ['Exportar CSV', 'Agendar Envio'],
  },
  // Aliases legados para retrocompatibilidade
  {
    slug: 'painel',
    titulo: 'Dashboard Marketing',
    subtitulo: 'Acompanhe campanhas, canais e conversões em tempo real.',
    icon: Gauge,
    grupo: 'marketing',
    tabs: ['Visão Geral', 'Metas de Marketing', 'Receita x Investimento', 'Conversões por Canal'],
    acoes: ['Nova Campanha', 'Enviar WhatsApp', 'Criar E-mail', 'Criar Cupom', 'Gerar UTM'],
  },
  {
    slug: 'campanhas-multicanal',
    titulo: 'Central de Campanhas Multicanal',
    subtitulo: 'Planeje, configure, dispare e acompanhe campanhas em múltiplos canais simultâneos.',
    icon: Megaphone,
    grupo: 'marketing',
    tabs: ['Todas', 'Ativas', 'Agendadas', 'Pausadas', 'Finalizadas', 'Rascunhos'],
    acoes: ['Nova Campanha', 'Usar Modelo', 'Importar Público'],
  },
  {
    slug: 'ga4',
    titulo: 'Google Analytics 4',
    subtitulo: 'Engajamento, funil de compras e e-commerce via Measurement Protocol.',
    icon: BarChart3,
    grupo: 'marketing',
    tabs: ['Visão Geral & Desempenho', 'Funil de Compras E-commerce', 'Canais de Aquisição GA4', 'DebugView em Tempo Real', 'Configuração GA4 & Protocolo'],
    acoes: ['Enviar Ping DebugView'],
  },
  {
    slug: 'utm-conversoes',
    titulo: 'Central UTM & Conversões',
    subtitulo: 'Atribuição, jornada e desempenho operacional de cada origem de tráfego.',
    icon: Link2,
    grupo: 'marketing',
    tabs: ['URLs Rastreáveis', 'Funil de Conversão', 'Evolução por Dia', 'Insights & Diagnóstico'],
    acoes: ['Exportar', 'Compartilhar', 'Nova UTM', 'Comparar URLs'],
  },
  {
    slug: 'ranking',
    titulo: 'Ranking de Campanhas',
    subtitulo: 'Comparação de ROI, ROAS, CPA e eficiência econômica de cada canal.',
    icon: Trophy,
    grupo: 'marketing',
    tabs: ['Ranking', 'ROI', 'ROAS', 'CPA'],
    acoes: ['Exportar Matriz'],
  },
];

export const remarketingScreens: VideoScreen[] = [
  {
    slug: 'dashboard',
    titulo: 'Dashboard Remarketing',
    subtitulo: 'Visão executiva de retenção, carrinhos recuperados e receita resgatada no Ledger.',
    icon: RotateCcw,
    grupo: 'remarketing',
    badge: 'MOTOR ATIVO',
    tabs: ['Dashboard', 'Funil de Resgate', 'Eficiência de Canais', 'Métricas em Tempo Real'],
    acoes: ['Recuperar Carrinhos', 'Nova Jornada', 'Exportar Métricas'],
  },
  {
    slug: 'publicos',
    titulo: 'Públicos Comportamentais',
    subtitulo: 'Audiências qualificadas com base em eventos de navegação, checkout e engajamento.',
    icon: Users,
    grupo: 'remarketing',
    tabs: ['Públicos Ativos', 'Sincronização Ads', 'Regras de Entrada', 'Exclusões'],
    acoes: ['Criar Público', 'Sincronizar Meta/Google'],
  },
  {
    slug: 'segmentos',
    titulo: 'Segmentos de Remarketing',
    subtitulo: 'Agrupamentos dinâmicos por perfil de compra, ticket médio e comportamento recente.',
    icon: Target,
    grupo: 'remarketing',
    badge: 'SEGMENTOS',
    tabs: ['Segmentos Ativos', 'Filtros Dinâmicos', 'Estimativa de Alcance', 'Histórico'],
    acoes: ['Novo Segmento', 'Exportar Base'],
  },
  {
    slug: 'jornadas',
    titulo: 'Jornadas de Remarketing',
    subtitulo: 'Motor visual de réguas automáticas: Gatilho → Condição → Espera → Canal → Conversão.',
    icon: Workflow,
    grupo: 'remarketing',
    badge: 'AUTOMAÇÃO',
    tabs: ['Jornadas Ativas', 'Construtor Visual', 'Gatilhos & Eventos', 'Logs de Execução'],
    acoes: ['Nova Jornada', 'Pausar/Ativar Fluxos', 'Testar Régua'],
  },
  {
    slug: 'carrinho',
    titulo: 'Carrinho Abandonado',
    subtitulo: 'Sessões interrompidas, valor potencial, origem UTM e ações imediatas de resgate.',
    icon: ShoppingCart,
    grupo: 'remarketing',
    badge: 'RESGATE 1-CLIQUE',
    tabs: ['Todos', 'Abertos', 'Disparados', 'Recuperados'],
    acoes: ['Recuperar Todos Abertos', 'Filtrar por Tempo', 'Disparar WhatsApp'],
  },
  {
    slug: 'visitou-nao-comprou',
    titulo: 'Visitou e Não Comprou',
    subtitulo: 'Leads que visualizaram páginas do evento sem iniciar carrinho nos últimos 7 dias.',
    icon: Eye,
    grupo: 'remarketing',
    tabs: ['Visitantes Recentes', 'Páginas Mais Acessadas', 'Retargeting Dinâmico', 'Taxa de Retorno'],
    acoes: ['Criar Audiência Retargeting', 'Ativar Push/Pixel'],
  },
  {
    slug: 'compradores',
    titulo: 'Compradores Anteriores',
    subtitulo: 'Base autorizada de edições passadas para pré-venda exclusiva e fidelização (LGPD).',
    icon: Users,
    grupo: 'remarketing',
    tabs: ['Edições Anteriores', 'Opt-in Válido', 'Histórico de Compras', 'Disparos VIP'],
    acoes: ['Convidar Compradores', 'Gerar Lote VIP'],
  },
  {
    slug: 'recorrentes',
    titulo: 'Clientes Recorrentes',
    subtitulo: 'Compradores com 2+ compras na DiskIngressos para programas de cashback e fidelidade.',
    icon: RotateCcw,
    grupo: 'remarketing',
    badge: 'VIP / RECORRÊNCIA',
    tabs: ['Clientes VIP', 'Métricas de LTV', 'Vantagens & Benefícios', 'Retenção'],
    acoes: ['Criar Campanha VIP', 'Exportar Lista'],
  },
  {
    slug: 'whatsapp',
    titulo: 'Recuperação por WhatsApp',
    subtitulo: 'Disparo de WhatsApp Oficial com link de checkout 1-clique e templates homologados.',
    icon: MessageCircle,
    grupo: 'remarketing',
    badge: 'WHATSAPP OFICIAL',
    tabs: ['Fila de Envios', 'Templates Aprovados', 'Conversões Diretas', 'Opt-out'],
    acoes: ['Disparo em Lote', 'Novo Template', 'Testar Envio'],
  },
  {
    slug: 'email',
    titulo: 'Recuperação por E-mail',
    subtitulo: 'E-mails transacionais e de resgate com cupom e contagem regressiva de reserva.',
    icon: Mail,
    grupo: 'remarketing',
    tabs: ['Campanhas de Resgate', 'Templates HTML', 'Entregabilidade SPF/DKIM', 'Métricas'],
    acoes: ['Criar E-mail Resgate', 'Validar Domínio'],
  },
  {
    slug: 'campanhas',
    titulo: 'Campanhas de Remarketing',
    subtitulo: 'Gerenciamento de anúncios e disparos voltados exclusivamente para reengajamento.',
    icon: Zap,
    grupo: 'remarketing',
    tabs: ['Campanhas Ativas', 'Orçamento & Lance', 'Desempenho por Canal', 'Audiências Conectadas'],
    acoes: ['Nova Campanha Remarketing', 'Pausar Todas'],
  },
  {
    slug: 'automacoes',
    titulo: 'Automações de Remarketing',
    subtitulo: 'Configuração de webhooks, integrações de gatilho e regras de resgate automático.',
    icon: Workflow,
    grupo: 'remarketing',
    tabs: ['Regras Ativas', 'Webhooks Recebidos', 'Histórico de Disparos', 'Falhas & Retentativas'],
    acoes: ['Nova Regra', 'Reprocessar Falhas'],
  },
  {
    slug: 'conversoes',
    titulo: 'Conversões Recuperadas',
    subtitulo: 'Auditoria de pedidos salvos, canal decisivo, tempo de resgate e correlação de receita.',
    icon: ShieldCheck,
    grupo: 'remarketing',
    badge: 'AUDITADO',
    tabs: ['Pedidos Resgatados', 'Auditoria Ledger', 'Atribuição de Canal', 'Exportação'],
    acoes: ['Exportar Auditoria', 'Verificar Ledger'],
  },
  {
    slug: 'relatorios',
    titulo: 'Relatórios de Remarketing',
    subtitulo: 'Relatórios consolidados de ROI, custo por recuperação e taxa de retenção por evento.',
    icon: FileBarChart,
    grupo: 'remarketing',
    tabs: ['Visão Executiva', 'ROI & Custos', 'Comparativo por Canal', 'Evolução Temporal'],
    acoes: ['Exportar Relatório PDF', 'Agendar Envio'],
  },
  // Aliases para máxima resiliência de rota
  {
    slug: 'carrinhos',
    titulo: 'Carrinho Abandonado',
    subtitulo: 'Sessões interrompidas, valor potencial, origem UTM e ações imediatas de resgate.',
    icon: ShoppingCart,
    grupo: 'remarketing',
    tabs: ['Todos', 'Abertos', 'Disparados', 'Recuperados'],
    acoes: ['Recuperar Todos Abertos'],
  },
  {
    slug: 'carrinho-abandonado',
    titulo: 'Carrinho Abandonado',
    subtitulo: 'Sessões interrompidas, valor potencial, origem UTM e ações imediatas de resgate.',
    icon: ShoppingCart,
    grupo: 'remarketing',
    tabs: ['Todos', 'Abertos', 'Disparados', 'Recuperados'],
    acoes: ['Recuperar Todos Abertos'],
  },
  {
    slug: 'compradores-anteriores',
    titulo: 'Compradores Anteriores',
    subtitulo: 'Base autorizada de edições passadas para pré-venda exclusiva e fidelização (LGPD).',
    icon: Users,
    grupo: 'remarketing',
    tabs: ['Edições Anteriores', 'Opt-in Válido', 'Histórico de Compras'],
    acoes: ['Convidar Compradores'],
  },
  {
    slug: 'clientes-recorrentes',
    titulo: 'Clientes Recorrentes',
    subtitulo: 'Compradores com 2+ compras na DiskIngressos para programas de cashback e fidelidade.',
    icon: RotateCcw,
    grupo: 'remarketing',
    tabs: ['Clientes VIP', 'Métricas de LTV', 'Retenção'],
    acoes: ['Criar Campanha VIP'],
  },
  {
    slug: 'recuperacao-whatsapp',
    titulo: 'Recuperação por WhatsApp',
    subtitulo: 'Disparo de WhatsApp Oficial com link de checkout 1-clique e templates homologados.',
    icon: MessageCircle,
    grupo: 'remarketing',
    tabs: ['Fila de Envios', 'Templates Aprovados', 'Conversões Diretas'],
    acoes: ['Disparo em Lote'],
  },
  {
    slug: 'recuperacao-email',
    titulo: 'Recuperação por E-mail',
    subtitulo: 'E-mails transacionais e de resgate com cupom e contagem regressiva de reserva.',
    icon: Mail,
    grupo: 'remarketing',
    tabs: ['Campanhas de Resgate', 'Templates HTML', 'Métricas'],
    acoes: ['Criar E-mail Resgate'],
  },
  {
    slug: 'conversoes-recuperadas',
    titulo: 'Conversões Recuperadas',
    subtitulo: 'Auditoria de pedidos salvos, canal decisivo, tempo de resgate e correlação de receita.',
    icon: ShieldCheck,
    grupo: 'remarketing',
    tabs: ['Pedidos Resgatados', 'Auditoria Ledger', 'Atribuição de Canal'],
    acoes: ['Exportar Auditoria'],
  },
  {
    slug: 'painel',
    titulo: 'Hub de Remarketing & Recuperação',
    subtitulo: 'Recupere carrinhos abandonados, Pix não pagos e reative clientes sem custo extra de tráfego.',
    icon: RotateCcw,
    grupo: 'remarketing',
    tabs: ['Dashboard', 'Carrinhos Abandonados', 'Recuperação de Pix & Pagamentos', 'Relatórios de Resgate'],
    acoes: ['Ver Carrinhos Abertos'],
  },
  {
    slug: 'pix-pagamentos',
    titulo: 'Recuperação de Pix & Pagamentos',
    subtitulo: 'Pix e cartões pendentes com timer, chave Pix e confirmação de venda.',
    icon: CreditCard,
    grupo: 'remarketing',
    tabs: ['Pendentes', 'Expirando', 'Em Recuperação', 'Recuperados'],
    acoes: ['Processar Pendências'],
  },
  {
    slug: 'regua-fluxos',
    titulo: 'Régua de Fluxos de Resgate',
    subtitulo: 'Jornadas automatizadas de recuperação em etapas e por canal.',
    icon: Workflow,
    grupo: 'remarketing',
    tabs: ['Fluxos Ativos', 'Etapas', 'Gatilhos', 'Histórico'],
    acoes: ['Nova Régua', 'Ativar Fluxo'],
  },
  {
    slug: 'clientes-inativos',
    titulo: 'Clientes Inativos',
    subtitulo: 'Reativação de compradores de edições anteriores, respeitando consentimento e LGPD.',
    icon: Users,
    grupo: 'remarketing',
    tabs: ['Inativos', 'Elegíveis', 'Reativados', 'Excluídos'],
    acoes: ['Criar Público de Reativação'],
  },
];

export const findVideoScreen = (grupo: 'marketing' | 'remarketing', slug: string) =>
  (grupo === 'marketing' ? marketingScreens : remarketingScreens).find((x) => x.slug === slug);
