import type { LucideIcon } from 'lucide-react';
import { Megaphone, MessageCircle, Mail, BarChart3, Music2, Activity, Link2, GitBranch, Trophy, ShoppingCart, Clock3, Workflow, Users, FileBarChart, CreditCard, RotateCcw, Target, Send, Gauge, Bot, ShieldCheck, Tags } from 'lucide-react';

export type VideoScreen = { slug:string; titulo:string; subtitulo:string; icon:LucideIcon; grupo:'marketing'|'remarketing'; tabs:string[]; acoes:string[] };
export const marketingScreens: VideoScreen[] = [
 {slug:'painel',titulo:'Marketing',subtitulo:'Acompanhe campanhas, canais e conversões em tempo real.',icon:Gauge,grupo:'marketing',tabs:['Visão Geral','Metas de Marketing','Receita x Investimento','Conversões por Canal'],acoes:['Nova Campanha','Enviar WhatsApp','Criar E-mail','Criar Cupom','Recuperar Carrinhos','Criar Público','Gerar UTM']},
 {slug:'campanhas-multicanal',titulo:'Central de Campanhas Multicanal',subtitulo:'Planeje, configure, dispare e acompanhe campanhas em múltiplos canais simultâneos.',icon:Megaphone,grupo:'marketing',tabs:['Todas','Ativas','Agendadas','Pausadas','Finalizadas','Rascunhos'],acoes:['Nova Campanha','Usar Modelo','Importar Público']},
 {slug:'whatsapp',titulo:'WhatsApp Marketing & CRM',subtitulo:'Disparos em massa, templates oficiais, recuperação de checkout e automações.',icon:MessageCircle,grupo:'marketing',tabs:['Campanhas de Disparo','Templates Oficiais & Live Preview','Jornadas & Automações','Histórico & Fila de Envios','Audiências & LGPD'],acoes:['Nova Campanha WhatsApp']},
 {slug:'email',titulo:'E-mail Marketing & CRM',subtitulo:'Disparos segmentados, testes A/B, templates responsivos e entregabilidade.',icon:Mail,grupo:'marketing',tabs:['Campanhas de E-mail','Templates Responsivos & Preview','Testes A/B & Automações','Logs SMTP & Entregabilidade','Segmentação de Leads'],acoes:['Novo Disparo de E-mail']},
 {slug:'status-real',titulo:'Status Real das Campanhas',subtitulo:'Status de entrega, análise, rejeições, diagnóstico e sincronização por canal.',icon:Activity,grupo:'marketing',tabs:['Meta Ads','Google Ads','TikTok Ads','Spotify Ads'],acoes:['Sincronizar','Diagnóstico']},
 {slug:'ga4',titulo:'Google Analytics 4',subtitulo:'Engajamento, funil de compras e e-commerce via Measurement Protocol.',icon:BarChart3,grupo:'marketing',tabs:['Visão Geral & Desempenho','Funil de Compras E-commerce','Canais de Aquisição GA4','DebugView em Tempo Real','Configuração GA4 & Protocolo'],acoes:['Enviar Ping DebugView']},
 {slug:'tiktok',titulo:'TikTok Ads & Pixel',subtitulo:'Campanhas em vídeo com rastreamento via TikTok Pixel & Events API.',icon:Activity,grupo:'marketing',tabs:['Campanhas & Spark Ads','Configuração do TikTok Pixel & Events API','Públicos Virais & Engajamento TikTok','Logs de Transmissão'],acoes:['Testar Conexão TikTok','Criar Spark Ad']},
 {slug:'spotify',titulo:'Spotify Ads & Conversões CAPI',subtitulo:'Campanhas de áudio, audiência, CAPI e atribuição de vendas por evento.',icon:Music2,grupo:'marketing',tabs:['Campanhas no Spotify','Atribuição de Vendas UTM','Spotify CAPI & Eventos','Comparativo Omnichannel'],acoes:['Sincronizar','Nova Campanha Spotify','Configurar Credenciais','Testar CAPI']},
 {slug:'utm-conversoes',titulo:'Central UTM & Conversões',subtitulo:'Atribuição, jornada e desempenho operacional de cada origem de tráfego.',icon:Link2,grupo:'marketing',tabs:['URLs Rastreáveis','Funil de Conversão','Evolução por Dia','Insights & Diagnóstico'],acoes:['Exportar','Compartilhar','Nova UTM','Comparar URLs']},
 {slug:'atribuicao',titulo:'Central de Atribuição Multicanal',subtitulo:'UTM, click IDs, campanhas, vendas, receita e ROAS em uma única visão.',icon:GitBranch,grupo:'marketing',tabs:['Último Clique','Primeiro Clique','Linear','Assistida'],acoes:['Sincronizar','Exportar']},
 {slug:'ranking',titulo:'Ranking de Campanhas',subtitulo:'Comparação de ROI, ROAS, CPA e eficiência econômica de cada canal.',icon:Trophy,grupo:'marketing',tabs:['Ranking','ROI','ROAS','CPA'],acoes:['Exportar Matriz']},
];
export const remarketingScreens: VideoScreen[] = [
 {slug:'painel',titulo:'Hub de Remarketing & Recuperação',subtitulo:'Recupere carrinhos abandonados, Pix não pagos e reative clientes sem custo extra de tráfego.',icon:RotateCcw,grupo:'remarketing',tabs:['Dashboard','Carrinhos Abandonados','Recuperação de Pix & Pagamentos','Régua de Fluxos de Resgate','WhatsApp Remarketing','E-mail Remarketing','Clientes Inativos','Relatórios de Resgate'],acoes:['Ver Carrinhos Abertos']},
 {slug:'carrinhos',titulo:'Carrinhos Abandonados',subtitulo:'Sessões interrompidas, valor potencial, origem UTM e ações de recuperação.',icon:ShoppingCart,grupo:'remarketing',tabs:['Todos','Abertos','Em Resgate','Recuperados'],acoes:['Processar Fila de Resgate']},
 {slug:'pix-pagamentos',titulo:'Recuperação de Pix & Pagamentos',subtitulo:'Pix e cartões pendentes com timer, chave Pix e confirmação de venda.',icon:CreditCard,grupo:'remarketing',tabs:['Pendentes','Expirando','Em Recuperação','Recuperados'],acoes:['Processar Pendências']},
 {slug:'regua-fluxos',titulo:'Régua de Fluxos de Resgate',subtitulo:'Jornadas automatizadas de recuperação em etapas e por canal.',icon:Workflow,grupo:'remarketing',tabs:['Fluxos Ativos','Etapas','Gatilhos','Histórico'],acoes:['Nova Régua','Ativar Fluxo']},
 {slug:'whatsapp',titulo:'WhatsApp Remarketing',subtitulo:'Histórico de mensagens de recuperação enviadas via WhatsApp Oficial.',icon:MessageCircle,grupo:'remarketing',tabs:['Todos','Abertos','Em Resgate','Recuperados'],acoes:['Processar Fila de Resgate']},
 {slug:'email',titulo:'E-mail Remarketing',subtitulo:'Jornadas e campanhas de retorno usando a base própria do produtor.',icon:Mail,grupo:'remarketing',tabs:['Campanhas','Templates','Automação','Entregabilidade'],acoes:['Novo Resgate por E-mail']},
 {slug:'clientes-inativos',titulo:'Clientes Inativos',subtitulo:'Reativação de compradores de edições anteriores, respeitando consentimento e LGPD.',icon:Users,grupo:'remarketing',tabs:['Inativos','Elegíveis','Reativados','Excluídos'],acoes:['Criar Público de Reativação']},
 {slug:'relatorios',titulo:'Relatórios de Resgate',subtitulo:'Performance, receita recuperada e atribuição UTM das ações de recuperação.',icon:FileBarChart,grupo:'remarketing',tabs:['Visão Geral','Canais','Eventos','Receita Recuperada'],acoes:['Exportar Relatório']},
];
export const findVideoScreen=(grupo:'marketing'|'remarketing',slug:string)=>(grupo==='marketing'?marketingScreens:remarketingScreens).find(x=>x.slug===slug);
