'use client';
import { useEffect,useState } from 'react'; import { useParams } from 'next/navigation'; import { Search,TicketCheck,ShoppingCart,CreditCard,RefreshCw } from 'lucide-react';
export default function Page(){
 const {eventoId}=useParams<{eventoId:string}>(); const [q,setQ]=useState(''); const [rows,setRows]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 async function load(term=''){setLoading(true);setError('');try{const r=await fetch(`/api/pedidos/evento/${eventoId}/consulta?q=${encodeURIComponent(term)}`,{cache:'no-store'});if(!r.ok)throw new Error(`API ${r.status}`);setRows(await r.json())}catch(e:any){setError(e.message||'Falha ao consultar pedidos')}finally{setLoading(false)}}
 useEffect(()=>{load()},[eventoId]);
 return <div className="space-y-4"><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-bold text-white">Ingressos & Pedidos</h2><p className="text-sm text-slate-400">Rastreabilidade real Pedido → Pagamento → Ingresso deste evento.</p></div><button onClick={()=>load(q)} className="rounded-lg border border-slate-700 px-3 py-2 text-sm text-slate-200 flex gap-2"><RefreshCw size={16}/>Atualizar</button></div>
 <form onSubmit={e=>{e.preventDefault();load(q)}} className="rounded-xl border border-slate-800 bg-[#0d1728] p-4 flex gap-2"><Search size={18} className="text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} className="bg-transparent outline-none flex-1 text-sm text-white" placeholder="Buscar nº do pedido, nome, CPF/documento ou telefone"/></form>
 <div className="grid md:grid-cols-3 gap-3">{[[ShoppingCart,'Pedidos','Pedido e condição comercial congelada'],[TicketCheck,'Ingressos únicos','Número individual e status'],[CreditCard,'Pagamentos','Transação e situação financeira']].map(([I,t,s]:any)=><div key={t} className="rounded-xl border border-slate-800 bg-[#0d1728] p-5"><I className="text-sky-400"/><h3 className="text-white font-semibold mt-3">{t}</h3><p className="text-sm text-slate-400 mt-1">{s}</p></div>)}</div>
 <div className="rounded-xl border border-slate-800 overflow-hidden"><div className="grid grid-cols-6 gap-2 bg-slate-900/70 p-3 text-xs text-slate-400"><span>Pedido</span><span>Comprador</span><span>Status</span><span>Total</span><span>Taxa Disk</span><span>Ingressos</span></div>{loading?<div className="p-8 text-center text-slate-400">Consultando transações...</div>:error?<div className="p-8 text-center text-rose-300">{error}</div>:rows.length===0?<div className="p-8 text-center text-slate-400">Nenhum pedido real encontrado para este evento.</div>:rows.map(r=><div key={r.id} className="grid grid-cols-6 gap-2 border-t border-slate-800 p-3 text-sm text-slate-200"><span>{r.numero}</span><span>{r.compradorNome}</span><span>{r.status}</span><span>R$ {Number(r.total).toFixed(2)}</span><span>R$ {Number(r.taxaDisk).toFixed(2)}</span><span>{r.ingressos?.length??0}</span></div>)}</div></div>
}
