'use client';
import {useEffect,useState} from 'react'; import {useParams} from 'next/navigation'; import {DollarSign,Ticket,Gift,CheckSquare,CreditCard,Landmark,Banknote,TrendingUp} from 'lucide-react';
const brl=(v:any)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0));
export default function Page(){const {eventoId}=useParams<{eventoId:string}>();const[d,setD]=useState<any>(null);useEffect(()=>{fetch(`/api/eventos/${eventoId}/os-resumo`,{cache:'no-store'}).then(r=>r.ok?r.json():null).then(setD).catch(()=>setD(null))},[eventoId]); const meios=d?.meiosPagamento||[];return <div className="space-y-5">
 <h1 className="text-2xl font-bold text-white">Dashboard</h1>
 <div className="grid md:grid-cols-4 rounded-xl border border-slate-700 bg-[#292b31] divide-x divide-slate-600"> <Top icon={DollarSign} value={brl(d?.gmv)} label="Total de Vendas"/><Top icon={Ticket} value={d?.ingressosVendidos??'—'} label="Vendidos"/><Top icon={Gift} value={d?.cortesias??'—'} label="Cortesias"/><Top icon={CheckSquare} value={d?.restantes??'—'} label="Restantes"/></div>
 <section className="rounded-xl border border-slate-700 bg-[#292b31]"><div className="p-5 border-b border-slate-600 flex justify-between"><h2 className="font-bold text-white text-lg">Ritmo de Vendas</h2><div className="flex"><button className="bg-sky-600 px-4 py-2 text-sm text-white">Financeiro</button><button className="border border-sky-600 px-4 py-2 text-sm text-sky-400">Quantidade</button></div></div><div className="grid lg:grid-cols-[320px_1fr] min-h-[330px]"><div className="p-6 border-r border-slate-600 space-y-6"><Mini label="TICKET MÉDIO" value={brl(d?.ticketMedio)}/><Mini label="PONTO DE EQUILÍBRIO" value={brl(d?.pontoEquilibrio)}/><Mini label="META DE VENDAS" value={brl(d?.metaVendas)}/><Mini label="PROJEÇÃO FINAL" value={brl(d?.projecaoFinal)}/></div><Chart values={d?.ritmoVendas}/></div></section>
 <div className="grid md:grid-cols-4 gap-4">{(meios.length?meios:[{nome:'Crédito'},{nome:'PIX'},{nome:'Débito'},{nome:'Dinheiro'}]).map((m:any,i:number)=><div key={m.nome} className="rounded-xl border border-slate-700 bg-[#292b31] p-5"><div className="text-xs uppercase text-slate-300">{m.nome}</div><div className="text-2xl font-bold text-white mt-2">{m.quantidade??'—'} <small className="text-sm font-normal">vendas</small></div><div className="text-lg text-sky-300 mt-3">{m.valor!=null?brl(m.valor):'—'}</div></div>)}</div>
 <div className="grid xl:grid-cols-2 gap-5"><Chart title="Quantidade por período" values={d?.quantidadePeriodo}/><Chart title="Valor (R$) por período" values={d?.valorPeriodo}/></div>
 <section className="rounded-xl border border-slate-700 bg-[#292b31] overflow-hidden"><h2 className="p-5 text-lg font-bold text-white border-b border-slate-600">Vendas por Modalidade</h2>{(d?.modalidades||[]).length?d.modalidades.map((m:any)=><div className="grid grid-cols-[1fr_160px_160px] p-4 border-b border-slate-700 text-sm"><b className="text-white">{m.nome}</b><span className="text-white text-right">{m.quantidade}</span><span className="text-sky-300 text-right">{brl(m.total)}</span></div>):<div className="p-8 text-slate-400">As modalidades aparecerão quando a API retornar vendas do evento.</div>}</section>
 </div>}
function Top({icon:I,value,label}:any){return <div className="p-6 flex gap-4 items-center"><I className="text-sky-400" size={36}/><div><div className="text-2xl font-bold text-white">{value}</div><div className="text-slate-300">{label}</div></div></div>}; function Mini({label,value}:any){return <div><div className="text-[11px] font-bold text-slate-300">{label}</div><div className="font-bold text-white mt-1">{value}</div></div>};
function Chart({title='Evolução financeira',values}:any){const v=Array.isArray(values)&&values.length?values.map((x:any)=>Number(x.valor??x)):[];return <div className="p-6 min-h-[280px] bg-[#292b31]"><h3 className="text-white font-semibold">{title}</h3><div className="h-[220px] mt-5 flex items-end gap-1 border-b border-l border-slate-600 p-3">{v.length?v.slice(-50).map((x:number,i:number)=>{const max=Math.max(...v,1);return <div key={i} className="flex-1 bg-sky-500/70 rounded-t" style={{height:`${Math.max(3,x/max*100)}%`}}/>}):<div className="m-auto text-sm text-slate-500">Aguardando dados reais da API deste evento.</div>}</div></div>}
