export type ActionPhase='IDLE'|'CONFIRMING'|'PROCESSING'|'SUCCESS'|'ERROR';
export type Provider='META'|'GOOGLE'|'TIKTOK'|'SPOTIFY'|'WHATSAPP'|'EMAIL';
export type MarketingAction='CONNECT'|'RECONNECT'|'DISCONNECT'|'SYNC'|'TEST_CONNECTION'|'CREATE_CAMPAIGN'|'SAVE_DRAFT'|'PUBLISH'|'EDIT'|'DUPLICATE'|'PAUSE'|'RESUME'|'STOP'|'CREATE_AUDIENCE'|'CREATE_CREATIVE'|'UPDATE_BUDGET'|'CONFIGURE_TRACKING'|'TEST_EVENT'|'DIAGNOSE'|'VIEW_LOGS'|'EXPORT'|'REFRESH_METRICS'|'CREATE_UTM'|'GENERATE_QR';
