'use client';
import React, { useMemo, useState } from 'react';
import Link from 'next/link';
import { Search, CalendarRange, FilePlus2, ArrowRight, Download, Clock3, LayoutGrid } from 'lucide-react';
import { reportGroups } from './reportCatalog';

const accent:any={orange:'text-orange-400 border-orange-500/20 bg-orange-500/5',blue:'text-blue-400 border-blue-500/20 bg-blue-500/5',emerald:'text-emerald-400 border-emerald-500/20 bg-emerald-500/5',violet:'text-violet-400 border-violet-500/20 bg-violet-500/5',pink:'text-pink-400 border-pink-500/20 bg-pink-500/5',yellow:'text-yellow-300 border-yellow-500/20 bg-yellow-500/5',red:'text-red-400 border-red-500/20 bg-red-500/5',cyan:'text-cyan-400 border-cyan-500/20 bg-cyan-500/5'};
export default function RelatoriosPage(){
 const [busca,setBusca]=useState('');
 const groups=useMemo(()=>reportGroups.map(g=>({...g,items:g.items.filter(i=>(i.title+' '+i.description).toLowerCase().includes(busca.toLowerCase()))})).filter(g=>g.items.length),[busca]);
 return <div className="p-5 lg:p-7 space-y-5 text-slate-100 max-w-[1800px] mx-auto">
  <header className="flex flex-col xl:flex-row xl:items-center justify-between gap-4"><div><div className="text-xs font-bold tracking-[.2em] text-blue-400 uppercase">Central exclusiva</div><h1 className="text-3xl font-bold mt-1">Relatórios</h1><p className="text-slate-400 mt-1">Painel de controle de relatórios de todas as áreas do EDDIE.</p></div><div className="flex flex-wrap gap-2"><button className="h-10 px-3 rounded-lg border border-slate-700 bg-slate-900 flex items-center gap-2 text-sm"><CalendarRange size={16}/>Período atual</button><Link href="/relatorios/personalizado" className="h-10 px-4 rounded-lg bg-blue-600 hover:bg-blue-500 flex items-center gap-2 text-sm font-semibold"><FilePlus2 size={16}/>Relatório personalizado</Link></div></header>
  <section className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3"><div className="metric"><LayoutGrid/> <span><b>{reportGroups.reduce((n,g)=>n+g.items.length,0)}</b><small>Modelos disponíveis</small></span></div><div className="metric"><Clock3/><span><b>Agendamentos</b><small>Programação de relatórios</small></span></div><div className="metric"><Download/><span><b>Exportações</b><small>CSV, JSON e impressão/PDF</small></span></div><div className="metric"><FilePlus2/><span><b>Personalizados</b><small>Filtros por produtor e evento</small></span></div></section>
  <div className="relative max-w-xl"><Search className="absolute left-3 top-3 text-slate-500" size={17}/><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar relatório..." className="w-full h-10 pl-10 pr-3 rounded-lg border border-slate-700 bg-slate-900 outline-none focus:border-blue-500 text-sm"/></div>
  <main className="space-y-5">{groups.map(g=>{const G=g.icon;return <section id={g.id} key={g.id} className={`rounded-2xl border p-3 lg:p-4 ${accent[g.accent]}`}><div className="flex items-center justify-between mb-3"><div className="flex items-center gap-3"><div className="p-2 rounded-lg bg-slate-950/50"><G size={20}/></div><div><h2 className="text-lg font-bold text-slate-100">{g.title}</h2><p className="text-xs text-slate-400">{g.description}</p></div></div><span className="text-xs font-semibold">{g.items.length} relatórios</span></div><div className="grid md:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-6 gap-2.5">{g.items.map(i=>{const I=i.icon;return <Link key={i.slug} href={`/relatorios/${g.id}/${i.slug}`} className="group min-h-[112px] rounded-xl border border-slate-700/70 bg-[#0d1728]/90 hover:bg-slate-800/80 hover:border-slate-600 p-3 transition flex flex-col"><div className="flex items-start justify-between"><I size={18}/><div className="flex gap-2 items-center">{i.badge&&<span className="text-[9px] px-1.5 py-0.5 rounded bg-emerald-500 text-slate-950 font-bold">{i.badge}</span>}<ArrowRight size={14} className="opacity-40 group-hover:opacity-100"/></div></div><div className="mt-3 text-sm font-semibold text-slate-100">{i.title}</div><p className="mt-1 text-[11px] leading-4 text-slate-400">{i.description}</p></Link>})}</div></section>})}</main>
  <style jsx>{`.metric{min-height:86px;border:1px solid rgb(51 65 85);background:rgba(15,23,42,.75);border-radius:14px;padding:16px;display:flex;gap:14px;align-items:center}.metric svg{color:#60a5fa}.metric span{display:flex;flex-direction:column}.metric b{font-size:18px;color:#f8fafc}.metric small{font-size:11px;color:#94a3b8;margin-top:3px}`}</style>
 </div>
}
