import { Wallet, CalendarDays, Scale, BriefcaseBusiness, Megaphone, Headphones, RotateCcw, Activity, FileText, Landmark, ArrowLeftRight, BadgeDollarSign, Target, Users, TicketCheck, MapPin, Layers3, BookOpen, ListChecks, Receipt, Percent, Banknote, TrendingUp, Link2, ShoppingCart, MessageCircle, Mail, Clock3, ShieldCheck, Gauge, UserCheck, FileClock, Building2 } from 'lucide-react';

export type ReportItem = { slug:string; title:string; description:string; icon:any; badge?:string };
export type ReportGroup = { id:string; title:string; description:string; accent:string; icon:any; items:ReportItem[] };
export const reportGroups: ReportGroup[] = [
 {id:'financeiro',title:'Financeiro',description:'Receitas, despesas, repasses, liquidação, conciliação e fluxo de caixa.',accent:'orange',icon:Wallet,items:[
  {slug:'receitas',title:'Relatório de Receitas',description:'Vendas, taxas e receitas reconhecidas por período.',icon:TrendingUp},{slug:'fluxo-caixa',title:'Fluxo de Caixa',description:'Entradas e saídas realizadas e previstas.',icon:Banknote},{slug:'repasse-evento',title:'Repasse por Evento',description:'Valores disponíveis, programados e liquidados.',icon:ArrowLeftRight},{slug:'antecipacoes',title:'Antecipações',description:'Solicitações, custos e liquidações.',icon:BadgeDollarSign},{slug:'conciliacao-bancaria',title:'Conciliação Bancária',description:'Extratos, divergências e situação da conciliação.',icon:Landmark},{slug:'comissoes-taxas',title:'Comissões e Taxas',description:'Taxas comerciais, meios de pagamento e custos.',icon:Percent},{slug:'extrato-periodo',title:'Extrato por Período',description:'Movimentações financeiras do período selecionado.',icon:ListChecks},{slug:'receitas-despesas',title:'Receitas e Despesas',description:'Visão consolidada por competência e evento.',icon:Receipt},{slug:'centro-custo',title:'Por Centro de Custo',description:'Lançamentos agrupados por centro de custo.',icon:Layers3},{slug:'fornecedores',title:'Fornecedores e Parceiros',description:'Receitas e despesas vinculadas a fornecedores.',icon:Building2},{slug:'cobrancas',title:'Histórico de Cobranças',description:'Cobranças, alterações e responsáveis.',icon:FileClock},{slug:'dre-financeira',title:'DRE Gerencial',description:'Resultado gerencial por evento e produtor.',icon:FileText}],},
 {id:'eventos',title:'Eventos',description:'Eventos, vendas, participantes, capacidade e desempenho.',accent:'blue',icon:CalendarDays,items:[
  {slug:'periodo',title:'Eventos por Período',description:'Status, datas, vendas e planejamento.',icon:CalendarDays},{slug:'vendas',title:'Vendas por Evento',description:'Ingressos, pedidos, faturamento e ticket médio.',icon:TrendingUp},{slug:'participantes',title:'Participantes',description:'Ingressos emitidos, check-ins e presença.',icon:Users},{slug:'setores-lotes',title:'Setores e Lotes',description:'Ocupação, disponibilidade e desempenho.',icon:Layers3},{slug:'receita',title:'Receita por Evento',description:'Receitas consolidadas por evento.',icon:Banknote},{slug:'comparativo',title:'Comparativo entre Eventos',description:'Compare vendas, finanças e indicadores.',icon:Scale,badge:'Novo'},{slug:'metas',title:'Metas do Evento',description:'Metas e evolução dos indicadores.',icon:Target},{slug:'custo-venda',title:'Custo de Venda',description:'Custos comerciais e operacionais por evento.',icon:Percent},{slug:'local',title:'Eventos por Salão/Local',description:'Histórico e resultados por local.',icon:MapPin},{slug:'pedidos',title:'Pedidos por Período',description:'Pedidos e produtos organizados por evento.',icon:TicketCheck}],},
 {id:'contabil',title:'Contábil',description:'Demonstrações, lançamentos, conciliação e fechamento.',accent:'emerald',icon:Scale,items:[
  {slug:'dre',title:'DRE',description:'Resultado contábil do período.',icon:FileText},{slug:'balancete',title:'Balancete',description:'Saldos e movimentações das contas.',icon:Scale},{slug:'livro-diario',title:'Livro Diário',description:'Lançamentos contábeis e partidas.',icon:BookOpen},{slug:'plano-contas',title:'Plano de Contas',description:'Estrutura e classificação contábil.',icon:ListChecks},{slug:'fechamento',title:'Fechamento Mensal',description:'Competências, aprovações e encerramento.',icon:FileClock},{slug:'demonstrativos',title:'Demonstrativos',description:'Balanço e demonstrativos gerenciais.',icon:FileText},{slug:'conciliacao',title:'Conciliação Contábil',description:'Conferência entre fatos financeiros e contábeis.',icon:ShieldCheck},{slug:'auditoria',title:'Auditoria Contábil',description:'Rastreabilidade e integridade dos lançamentos.',icon:UserCheck}],},
 {id:'comercial',title:'Comercial B2B',description:'Produtores, oportunidades, propostas, contratos e metas.',accent:'violet',icon:BriefcaseBusiness,items:[
  {slug:'leads',title:'Leads e Oportunidades',description:'Pipeline comercial e conversão.',icon:Users},{slug:'propostas',title:'Propostas Comerciais',description:'Propostas, valores e situação.',icon:FileText},{slug:'contratos',title:'Contratos',description:'Contratos ativos, encerrados e ativações.',icon:ShieldCheck},{slug:'produtores',title:'Produtores',description:'Carteira B2B e relacionamento.',icon:Building2},{slug:'metas',title:'Metas Comerciais',description:'Atingimento e evolução de metas.',icon:Target},{slug:'atividades',title:'Atividades e Follow-ups',description:'Agenda e interações comerciais.',icon:Clock3}],},
 {id:'marketing',title:'Marketing',description:'Campanhas, canais, UTMs, conversões e remarketing.',accent:'pink',icon:Megaphone,items:[
  {slug:'campanhas',title:'Campanhas',description:'Desempenho por campanha e canal.',icon:Megaphone},{slug:'utm',title:'UTM e Links',description:'Tráfego, origem e conversões.',icon:Link2},{slug:'conversoes',title:'Conversões',description:'Pedidos e receita atribuída.',icon:Target},{slug:'carrinho',title:'Carrinho Abandonado',description:'Recuperação e receita recuperada.',icon:ShoppingCart},{slug:'whatsapp-email',title:'WhatsApp e E-mail',description:'Envios, entregas, cliques e resultados.',icon:MessageCircle},{slug:'roi',title:'ROI de Marketing',description:'Investimento, receita, ROAS e CPA.',icon:TrendingUp},{slug:'pixels',title:'Pixels e Tracking',description:'Saúde de tracking e eventos de conversão.',icon:Activity},{slug:'cupons',title:'Cupons',description:'Uso, pedidos e receita por cupom.',icon:TicketCheck}],},
 {id:'sac',title:'SAC',description:'Atendimento, tickets, SLA e satisfação.',accent:'yellow',icon:Headphones,items:[
  {slug:'tickets',title:'Tickets por Período',description:'Volume, situação e canal de atendimento.',icon:Headphones},{slug:'sla',title:'Tempo de Resposta',description:'SLA, primeira resposta e resolução.',icon:Clock3},{slug:'satisfacao',title:'CSAT e NPS',description:'Indicadores de satisfação.',icon:Gauge},{slug:'motivos',title:'Motivos de Contato',description:'Categorias e recorrência de chamados.',icon:ListChecks},{slug:'atendentes',title:'Atendentes',description:'Volume e desempenho operacional.',icon:UserCheck},{slug:'historico',title:'Histórico de Atendimentos',description:'Evolução dos atendimentos no período.',icon:FileClock}],},
 {id:'estornos',title:'Estornos',description:'Solicitações, aprovações, execução e auditoria.',accent:'red',icon:RotateCcw,items:[
  {slug:'solicitacoes',title:'Solicitações de Estorno',description:'Pedidos e situação das solicitações.',icon:RotateCcw},{slug:'valores',title:'Valores Estornados',description:'Valores solicitados e efetivamente estornados.',icon:Banknote},{slug:'motivos',title:'Motivos de Estorno',description:'Distribuição por motivo e origem.',icon:ListChecks},{slug:'sla',title:'SLA de Estornos',description:'Tempo de análise e execução.',icon:Clock3}],},
 {id:'operacional',title:'Operacional',description:'Visão geral, suporte, auditoria e saúde do sistema.',accent:'cyan',icon:Activity,items:[
  {slug:'visao-geral',title:'Visão Geral',description:'Indicadores operacionais consolidados.',icon:Gauge},{slug:'suporte',title:'Suporte a Eventos',description:'Ocorrências, prioridade e SLA.',icon:Headphones},{slug:'auditoria',title:'Auditoria',description:'Ações e rastreabilidade operacional.',icon:ShieldCheck},{slug:'integracoes',title:'Integrações',description:'Situação dos serviços e integrações.',icon:Activity},{slug:'performance',title:'Performance do Sistema',description:'Disponibilidade e desempenho técnico.',icon:Gauge}],},
];
export const allReports = reportGroups.flatMap(g=>g.items.map(i=>({...i,groupId:g.id,groupTitle:g.title})));
