'use client';
import React from 'react';
import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';

export type ChartPoint={label:string;value:number};
const nf=new Intl.NumberFormat('pt-BR',{notation:'compact',maximumFractionDigits:1});
export function LineChartCard({title,subtitle,points,valueFormatter=(v)=>nf.format(v)}:{title:string;subtitle?:string;points:ChartPoint[];valueFormatter?:(v:number)=>string}){
 const data=points.slice(-12); const max=Math.max(1,...data.map(x=>Math.abs(x.value))); const coords=data.map((p,i)=>`${data.length===1?50:(i/(data.length-1))*100},${92-(Math.max(0,p.value)/max)*72}`).join(' ');
 return <div className="rounded-2xl border border-slate-800 bg-slate-900/80 p-5"><div className="mb-4"><h3 className="font-semibold text-white">{title}</h3>{subtitle&&<p className="text-xs text-slate-500">{subtitle}</p>}</div>{data.length?<><svg viewBox="0 0 100 100" className="h-48 w-full" preserveAspectRatio="none"><defs><linearGradient id={`g-${title.replace(/\W/g,'')}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="currentColor" stopOpacity=".25"/><stop offset="100%" stopColor="currentColor" stopOpacity="0"/></linearGradient></defs><path d={`M ${coords.split(' ').join(' L ')} L 100 100 L 0 100 Z`} fill={`url(#g-${title.replace(/\W/g,'')})`} className="text-sky-400"/><polyline points={coords} fill="none" stroke="currentColor" strokeWidth="2" vectorEffect="non-scaling-stroke" className="text-sky-400"/></svg><div className="mt-2 flex justify-between gap-2 text-[10px] text-slate-500">{data.filter((_,i)=>i===0||i===data.length-1||i===Math.floor(data.length/2)).map((p,i)=><span key={`${p.label}-${i}`}>{p.label}<b className="ml-1 text-slate-300">{valueFormatter(p.value)}</b></span>)}</div></>:<Empty/>}</div>
}
export function BarChartCard({title,subtitle,points,valueFormatter=(v)=>nf.format(v)}:{title:string;subtitle?:string;points:ChartPoint[];valueFormatter?:(v:number)=>string}){const data=points.slice(0,8);const max=Math.max(1,...data.map(x=>Math.abs(x.value)));return <div className="rounded-2xl border border-slate-800 bg-slate-900/80 p-5"><h3 className="font-semibold text-white">{title}</h3>{subtitle&&<p className="mb-4 text-xs text-slate-500">{subtitle}</p>}<div className="space-y-3">{data.length?data.map((p,i)=><div key={`${p.label}-${i}`}><div className="mb-1 flex justify-between gap-3 text-xs"><span className="truncate text-slate-400">{p.label}</span><b className="text-slate-200">{valueFormatter(p.value)}</b></div><div className="h-2 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-sky-500" style={{width:`${Math.max(2,(Math.abs(p.value)/max)*100)}%`}}/></div></div>):<Empty/>}</div></div>}
export function DonutCard({title,subtitle,points,valueFormatter=(v)=>nf.format(v)}:{title:string;subtitle?:string;points:ChartPoint[];valueFormatter?:(v:number)=>string}){const data=points.filter(x=>x.value>0).slice(0,5);const total=data.reduce((s,x)=>s+x.value,0);let acc=0;return <div className="rounded-2xl border border-slate-800 bg-slate-900/80 p-5"><h3 className="font-semibold text-white">{title}</h3>{subtitle&&<p className="text-xs text-slate-500">{subtitle}</p>}<div className="mt-4 grid grid-cols-[130px_1fr] items-center gap-5">{total>0?<svg viewBox="0 0 42 42" className="h-32 w-32 -rotate-90">{data.map((p,i)=>{const pct=p.value/total*100;const start=acc;acc+=pct;return <circle key={p.label} cx="21" cy="21" r="15.9155" fill="transparent" stroke="currentColor" strokeWidth="6" strokeDasharray={`${pct} ${100-pct}`} strokeDashoffset={-start} className={['text-sky-500','text-emerald-500','text-amber-500','text-violet-500','text-rose-500'][i]}/>})}</svg>:<div className="grid h-32 w-32 place-items-center rounded-full border-8 border-slate-800 text-xs text-slate-500">Sem dados</div>}<div className="space-y-2">{data.map((p,i)=><div key={p.label} className="flex items-center justify-between gap-3 text-xs"><span className="flex min-w-0 items-center gap-2 text-slate-400"><i className={`h-2 w-2 shrink-0 rounded-full ${['bg-sky-500','bg-emerald-500','bg-amber-500','bg-violet-500','bg-rose-500'][i]}`}/><span className="truncate">{p.label}</span></span><b className="text-slate-200">{valueFormatter(p.value)}</b></div>)}</div></div></div>}
export function QuickActions({title='Atalhos',items}:{title?:string;items:{label:string;href:string;description?:string}[]}){return <div className="rounded-2xl border border-slate-800 bg-slate-900/80 p-5"><h3 className="mb-3 font-semibold text-white">{title}</h3><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-1">{items.map(x=><Link key={x.href+x.label} href={x.href} className="group flex items-center justify-between rounded-xl border border-slate-800 bg-slate-950/60 p-3 hover:border-sky-700"><div><div className="text-sm font-semibold text-slate-200">{x.label}</div>{x.description&&<div className="text-xs text-slate-500">{x.description}</div>}</div><ArrowUpRight size={16} className="text-slate-600 group-hover:text-sky-400"/></Link>)}</div></div>}
function Empty(){return <div className="grid min-h-32 place-items-center text-sm text-slate-500">Sem dados reais para o período.</div>}
