'use client';
import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {AlertTriangle,RefreshCcw,TrendingUp,MousePointerClick,ShoppingCart,WalletCards,Target,Activity} from 'lucide-react';
import {useProducerEvent} from './ProducerEventContext';
import {BarChartCard,DonutCard,LineChartCard,QuickActions} from './ExecutiveCharts';
type Payload={kpis:Record<string,number|null>;rows:any[];channels:any[];notices:string[]};
const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v||0);
export default function MarketingExecutiveDashboard({grupo}:{grupo:'marketing'|'remarketing'}){const {api,produtorId,eventoId}=useProducerEvent();const [data,setData]=useState<Payload|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const load=useCallback(async()=>{if(!api||!produtorId){setLoading(false);return}setLoading(true);setError('');const c=new AbortController();const t=setTimeout(()=>c.abort(),5000);try{const q=new URLSearchParams({produtorId});if(eventoId)q.set('eventoId',eventoId);const r=await fetch(`${api}/marketing/video/${grupo}/painel?${q}`,{signal:c.signal});if(!r.ok)throw new Error(`API respondeu ${r.status}`);setData(await r.json())}catch(e:any){setError(e?.name==='AbortError'?'Tempo limite na consulta.':e?.message||'Falha na consulta.')}finally{clearTimeout(t);setLoading(false)}},[api,produtorId,eventoId,grupo]);useEffect(()=>{load()},[load]);
 const k=data?.kpis||{};const cards=[['Campanhas ativas',k.campanhas_ativas||0,Activity],['Investimento',money(Number(k.investimento||0)),WalletCards],['Receita atribuída',money(Number(k.receita_atribuida||0)),TrendingUp],['Conversões',k.conversoes||0,ShoppingCart],['Cliques',k.cliques||0,MousePointerClick],['ROAS',k.roas==null?'—':`${Number(k.roas).toFixed(2)}x`,Target]] as const;
 const channels=useMemo(()=>{const m=new Map<string,number>();(data?.rows||[]).forEach((r:any)=>{for(const c of (r.canais||[r.canal||r.origem||r.provedor||'Outros']))m.set(String(c), (m.get(String(c))||0)+Number(r.gastoAtual||r.receitaAtribuida||r.cliques||1))});return [...m].map(([label,value])=>({label,value})).sort((a,b)=>b.value-a.value)},[data]);
 const trend=useMemo(()=>{const m=new Map<string,number>();(data?.rows||[]).forEach((r:any)=>{const d=String(r.createdAt||r.atribuidaEm||'').slice(5,10);if(d)m.set(d,(m.get(d)||0)+Number(r.receitaAtribuida||r.gastoAtual||r.cliques||1))});return [...m].sort(([a],[b])=>a.localeCompare(b)).map(([label,value])=>({label,value}))},[data]);
 const actions=grupo==='marketing'?[{label:'Nova campanha',href:'/marketing/campanhas-multicanal'},{label:'WhatsApp Marketing',href:'/marketing/whatsapp'},{label:'E-mail Marketing',href:'/marketing/email'},{label:'UTMs & Conversões',href:'/marketing/utm-conversoes'},{label:'Atribuição',href:'/marketing/atribuicao'},{label:'Status das campanhas',href:'/marketing/status-real'}]:[{label:'Carrinhos abandonados',href:'/remarketing/carrinhos'},{label:'PIX & pagamentos',href:'/remarketing/pix-pagamentos'},{label:'Régua de resgate',href:'/remarketing/regua-fluxos'},{label:'WhatsApp Remarketing',href:'/remarketing/whatsapp'},{label:'E-mail Remarketing',href:'/remarketing/email'},{label:'Relatórios de resgate',href:'/remarketing/relatorios'}];
 return <div className="space-y-4">{error&&<div className="flex gap-2 rounded-xl border border-amber-700/40 bg-amber-950/20 p-3 text-sm text-amber-200"><AlertTriangle size={17}/>{error} Nenhuma métrica foi simulada.</div>}<div className="flex justify-end"><button onClick={load} className="inline-flex items-center gap-2 rounded-lg border border-slate-700 px-3 py-2 text-xs text-slate-300"><RefreshCcw size={14} className={loading?'animate-spin':''}/>Atualizar dashboard</button></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{cards.map(([label,value,I])=><div key={label} className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><I size={18} className="mb-3 text-sky-400"/><div className="text-[10px] font-bold uppercase tracking-wide text-slate-500">{label}</div><div className="mt-1 text-xl font-bold text-white">{loading?'…':value}</div></div>)}</div><div className="grid gap-4 xl:grid-cols-3"><div className="xl:col-span-2"><LineChartCard title={grupo==='marketing'?'Evolução de performance':'Evolução de recuperação'} subtitle="Somente dados registrados no EDDIE" points={trend}/></div><QuickActions items={actions}/></div><div className="grid gap-4 lg:grid-cols-2"><BarChartCard title="Desempenho por canal/origem" subtitle="Comparativo operacional" points={channels}/><DonutCard title="Distribuição dos canais" subtitle="Participação nos registros do período" points={channels}/></div></div>}
