'use client';
import React,{useCallback,useEffect,useMemo,useState} from 'react';
import { AlertTriangle, ArrowLeft, CheckCircle2, RefreshCcw, Search, TrendingUp, WalletCards, MousePointerClick, ShoppingCart, Target, BarChart3, ExternalLink } from 'lucide-react';
import Link from 'next/link';
import { useProducerEvent } from './ProducerEventContext';
import type { VideoScreen } from '../lib/marketingVideoCatalog';
import { ModuleNavigation } from './navigation/ModuleNavigation';
import { CompactOperationalAlert } from './navigation/CompactOperationalAlert';

type Payload={screen:string; source:string; generatedAt:string; kpis:Record<string,number|string|null>; rows:Array<Record<string,unknown>>; channels:Array<Record<string,unknown>>; notices:string[]};
const fmt=(v:unknown)=> typeof v==='number'?new Intl.NumberFormat('pt-BR').format(v):String(v??'—');
export default function MarketingVideoScreen({config}:{config:VideoScreen}){
 const {api,produtorId,eventoId,evento}=useProducerEvent(); const [data,setData]=useState<Payload|null>(null); const [loading,setLoading]=useState(true); const [err,setErr]=useState(''); const [tab,setTab]=useState(config.tabs[0]);
 const load=useCallback(async()=>{ if(!api||!produtorId){setLoading(false);return;} setLoading(true);setErr(''); const c=new AbortController(); const t=setTimeout(()=>c.abort(),5000); try{const q=new URLSearchParams({produtorId}); if(eventoId)q.set('eventoId',eventoId); const r=await fetch(`${api}/marketing/video/${config.grupo}/${config.slug}?${q}`,{signal:c.signal}); if(!r.ok) throw new Error(`API respondeu ${r.status}`); setData(await r.json());}catch(e:any){setErr(e?.name==='AbortError'?'Tempo limite ao consultar dados reais.':e?.message||'Falha ao consultar dados.');}finally{clearTimeout(t);setLoading(false)}},[api,produtorId,eventoId,config.grupo,config.slug]);
 useEffect(()=>{load()},[load]); const Icon=config.icon; const kpis=useMemo(()=>Object.entries(data?.kpis||{}).slice(0,6),[data]);
 return <div className="space-y-5 p-4 md:p-6">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><Link href={config.grupo==='marketing'?'/marketing':'/remarketing'} className="mb-2 inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white"><ArrowLeft size={15}/> Voltar ao menu {config.grupo==='marketing'?'Marketing':'Remarketing'}</Link><div className="flex items-center gap-3"><div className="rounded-xl border border-slate-700 bg-slate-900 p-3"><Icon size={24}/></div><div><h1 className="text-2xl font-bold text-white">{config.titulo}</h1><p className="text-sm text-slate-400">{config.subtitulo}</p></div></div></div><button onClick={load} className="inline-flex items-center gap-2 rounded-lg border border-slate-700 px-4 py-2 text-sm text-slate-200"><RefreshCcw size={15}/>Atualizar</button></div>
  <div className="rounded-xl border border-slate-800 bg-slate-950/50 p-4"><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-semibold uppercase text-slate-500">Contexto:</span><span className="rounded-md bg-slate-800 px-2 py-1 text-xs text-slate-200">{evento?.nome||'Todos os eventos'}</span>{config.acoes.map(a=><button key={a} className="rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-xs font-semibold text-slate-200 hover:border-slate-500">{a}</button>)}</div></div>
  {err&&<div className="py-1"><CompactOperationalAlert status="degraded" title="Dados indisponíveis" detail={`${err} A tela permanece funcional sem métricas fictícias.`} onOpen={()=>alert(`${err}\nA tela permanece funcional sem métricas fictícias.`)}/></div>}
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{loading?Array.from({length:6}).map((_,i)=><div key={i} className="h-28 animate-pulse rounded-xl border border-slate-800 bg-slate-900"/>):kpis.length?kpis.map(([k,v],i)=>{const I=[WalletCards,MousePointerClick,ShoppingCart,Target,TrendingUp,BarChart3][i%6];return <div key={k} className="rounded-xl border border-slate-800 bg-slate-900 p-4"><I size={18} className="mb-3 text-sky-400"/><div className="text-xs uppercase text-slate-500">{k.replaceAll('_',' ')}</div><div className="mt-1 text-xl font-bold text-white">{fmt(v)}</div></div>}):<div className="col-span-full rounded-xl border border-slate-800 bg-slate-900 p-6 text-sm text-slate-400">Sem métricas reais para os filtros selecionados.</div>}</div>
  <ModuleNavigation items={config.tabs.map((x) => ({ id: x, label: x }))} activeItem={tab} onSelect={(id) => setTab(id)} ariaLabel={`Abas de ${config.titulo}`} />
  <div className="grid gap-4 xl:grid-cols-[1fr_340px]"><section className="rounded-xl border border-slate-800 bg-slate-900"><div className="flex items-center justify-between border-b border-slate-800 p-4"><div><h2 className="font-semibold text-white">{tab}</h2><p className="text-xs text-slate-500">Dados operacionais do EDDIE • sem valores demonstrativos</p></div><div className="flex items-center gap-2 rounded-lg border border-slate-700 px-3 py-2 text-xs text-slate-400"><Search size={14}/>Filtrar</div></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs uppercase text-slate-500"><tr><th className="p-4">Item</th><th className="p-4">Canal/Origem</th><th className="p-4">Status</th><th className="p-4 text-right">Valor/Métrica</th><th className="p-4">Ações</th></tr></thead><tbody>{(data?.rows||[]).map((r,i)=><tr key={i} className="border-t border-slate-800"><td className="p-4 font-medium text-slate-200">{String(r.nome||r.campanha||r.codigo||r.id||'Registro')}</td><td className="p-4 text-slate-400">{String(r.canal||r.origem||r.provedor||'—')}</td><td className="p-4"><span className="rounded-full bg-slate-800 px-2 py-1 text-xs text-slate-300">{String(r.status||'registrado')}</span></td><td className="p-4 text-right text-slate-200">{fmt(r.receita??r.valor??r.cliques??r.total??'—')}</td><td className="p-4"><button className="inline-flex items-center gap-1 text-xs text-sky-400">Abrir <ExternalLink size={12}/></button></td></tr>)}{!loading&&!data?.rows?.length&&<tr><td colSpan={5} className="p-10 text-center text-slate-500">Nenhum registro real encontrado para este contexto.</td></tr>}</tbody></table></div></section>
  <aside className="space-y-4"><div className="rounded-xl border border-slate-800 bg-slate-900 p-4"><h3 className="mb-3 font-semibold text-white">Canais e integrações</h3>{(data?.channels||[]).length?(data?.channels||[]).map((c,i)=><div key={i} className="mb-2 flex items-center justify-between rounded-lg bg-slate-950 p-3 text-sm"><span className="text-slate-300">{String(c.nome||c.canal||c.provedor||'Canal')}</span><span className="text-xs text-emerald-400">{String(c.status||'configurado')}</span></div>):<p className="text-sm text-slate-500">Nenhuma integração com dados reais encontrada.</p>}</div><div className="rounded-xl border border-slate-800 bg-slate-900 p-4"><h3 className="mb-3 font-semibold text-white">Diagnóstico</h3>{(data?.notices||['Nenhuma ocorrência crítica.']).map((n,i)=><div key={i} className="mb-2 flex gap-2 text-sm text-slate-400"><CheckCircle2 size={16} className="mt-0.5 shrink-0 text-emerald-500"/>{n}</div>)}</div></aside></div>
 </div>
}
