export const MARKETING_VIDEO_NAV = [
{key:'dashboard',label:'Dashboard Marketing'},
{key:'campanhas',label:'Campanhas Multicanais'},
{key:'campanhas-prontas',label:'Campanhas Prontas',badge:'PRONTO'},
{key:'status-real',label:'Status Real',badge:'AO VIVO'},
{key:'meta',label:'Meta Ads & Pixel',badge:'CAPI'},
{key:'google-analytics',label:'Google Analytics',badge:'GA4'},
{key:'tiktok',label:'TikTok Ads',badge:'PIXEL'},
{key:'spotify',label:'Spotify Ads',badge:'ÁUDIO'},
{key:'whatsapp',label:'WhatsApp Marketing',badge:'OFICIAL'},
{key:'email',label:'E-mail Marketing'},
{key:'automacoes',label:'Automações & Jornadas'},
{key:'cupons',label:'Cupons & Descontos'},
{key:'utm',label:'Central UTM & Links',badge:'UTM / QR'},
{key:'afiliados',label:'Afiliados & Promoters'},
{key:'pixels',label:'Pixels & Conversões',badge:'MULTI-PIXEL'},
{key:'atribuicao',label:'Atribuição Multicanal'},
{key:'relatorios',label:'Relatórios de Marketing'},
] as const;
